language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_frontender/ framework/app/libraries/li3_frontender
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium
  - git remote set-url origin git://github.com/mdx-dev/lithium.git
  - git fetch origin && git reset --hard origin/master
  - cd ../../app
  - cp libraries/li3_frontender/li3-composer.json composer.json
  - composer install
  - cd libraries/li3_frontender

script: ../../../libraries/lithium/console/li3 test tests
